namespace Smart.AspNetCore.Generator;

using System;
using System.Collections.Generic;
using System.Text;

using Smart.AspNetCore.Generator.Models;

using SourceGenerateHelper;

internal static class BindMethodSourceBuilder
{
    public static void BuildSource(SourceBuilder builder, List<MethodModel> methods)
    {
        var ns = methods[0].Namespace;
        var isValueType = methods[0].IsValueType;
        var isStatic = methods[0].IsStatic;
        var className = methods[0].ClassName;

        builder.AutoGenerated();
        builder.EnableNullable();
        builder.NewLine();

        // namespace
        if (!String.IsNullOrEmpty(ns))
        {
            builder.Namespace(ns);
            builder.NewLine();
        }

        // class
        builder
            .Indent()
            .Append(isStatic ? "static " : string.Empty)
            .Append("partial ")
            .Append(isValueType ? "struct " : "class ")
            .Append(className)
            .NewLine();
        builder.BeginScope();

        // method
        foreach (var method in methods)
        {
            BuildMethod(builder, method);
        }

        builder.EndScope();
    }

    private static void BuildMethod(SourceBuilder builder, MethodModel method)
    {
        builder
            .Indent()
            .Append(method.MethodAccessibility.ToText())
            .Append(" static partial ")
            .Append(method.ReturnTypeName)
            .Append(" ")
            .Append(method.MethodName)
            .Append("(");

        if (method.IsExtensionMethod)
        {
            builder.Append("this ");
        }

        builder
            .Append(method.SourceTypeName)
            .Append(" ")
            .Append(method.SourceParameterName);

        if (method.Pattern != BindingPattern.Factory)
        {
            builder
                .Append(", ")
                .Append(method.TargetTypeName)
                .Append(" target");
        }

        builder.Append(")").NewLine();
        builder.BeginScope();

        // Create instance if factory pattern
        if (method.Pattern == BindingPattern.Factory)
        {
            builder
                .Indent()
                .Append("var target = new ")
                .Append(method.ReturnTypeName)
                .Append("();")
                .NewLine();
            builder.NewLine();
        }

        // Property bindings
        var properties = method.Properties;
        for (var index = 0; index < properties.Count; index++)
        {
            BuildProperty(builder, method, properties[index], index);
            builder.NewLine();
        }

        // Return target if factory or return-instance
        if (method.Pattern != BindingPattern.Instance)
        {
            builder
                .Indent()
                .Append("return target;")
                .NewLine();
        }

        builder.EndScope();
        builder.NewLine();
    }

    private static void BuildProperty(SourceBuilder builder, MethodModel method, PropertyModel property, int index)
    {
        var valueName = "p" + index;

        // Bind if value exists in the source and is not empty
        builder
            .Indent()
            .Append("if (")
            .Append(method.SourceParameterName)
            .Append(".TryGetValue(\"")
            .Append(property.Name)
            .Append("\", out var ")
            .Append(valueName)
            .Append(") &&")
            .NewLine()
            .Indent()
            .Append("    ")
            .Append(GetHasValueExpression(method.SourceValueKind, valueName))
            .Append(")")
            .NewLine();
        builder.BeginScope();

        // Bind by property kind
        switch (property.ValueKind)
        {
            case PropertyValueKind.String:
                // Directly assign from source
                builder
                    .Indent()
                    .Append("target.")
                    .Append(property.Name)
                    .Append(" = ")
                    .Append(GetSingleValueExpression(method.SourceValueKind, valueName))
                    .Append(";")
                    .NewLine();
                break;
            case PropertyValueKind.StringArray:
                // Directly assign from all source values
                builder
                    .Indent()
                    .Append("target.")
                    .Append(property.Name)
                    .Append(" = ")
                    .Append(GetArrayValueExpression(method.SourceValueKind, valueName))
                    .Append(";")
                    .NewLine();
                break;
            case PropertyValueKind.Array:
                // Convert each element for non-string arrays
                BuildArrayProperty(builder, method, property, valueName);
                break;
            default:
                // Convert from single source
                BuildSingleConvertedProperty(builder, method, property, valueName);
                break;
        }

        builder.EndScope();
    }

    private static void BuildArrayProperty(SourceBuilder builder, MethodModel method, PropertyModel property, string valueName)
    {
        if (property.ConverterMethodName is null)
        {
            return;
        }

        var arrName = valueName + "arr";
        var countExpr = GetCountExpression(method.SourceValueKind, valueName);
        var elementType = GetArrayElementCreationType(property.TypeName, property.AssignmentTypeName);

        // Allocate result array
        builder
            .Indent()
            .Append("var ")
            .Append(arrName)
            .Append(" = new ")
            .Append(elementType)
            .Append("[")
            .Append(countExpr)
            .Append("];")
            .NewLine();

        // Loop over source values and convert each element
        builder
            .Indent()
            .Append("for (var i = 0; i < ")
            .Append(countExpr)
            .Append("; i++)")
            .NewLine();
        builder.BeginScope();

        if (method.Strict && (property.ConverterMethodTypeName == BindMethodModelBuilder.DefaultConverterTypeName))
        {
            AppendStrictConversion(builder, property, GetIndexedSpanExpression(method.SourceValueKind, valueName, "i"), arrName + "[i]", valueName + "e");
        }
        else
        {
            builder
                .Indent()
                .Append(arrName)
                .Append("[i] = ");
            AppendConvertCall(builder, property, GetIndexedSpanExpression(method.SourceValueKind, valueName, "i"));
            builder.Append(";").NewLine();
        }

        builder.EndScope();

        // Assign to property
        builder
            .Indent()
            .Append("target.")
            .Append(property.Name)
            .Append(" = ")
            .Append(arrName)
            .Append(";")
            .NewLine();
    }

    private static void BuildSingleConvertedProperty(SourceBuilder builder, MethodModel method, PropertyModel property, string valueName)
    {
        if (property.ConverterMethodName is null)
        {
            return;
        }

        if (method.Strict && (property.ConverterMethodTypeName == BindMethodModelBuilder.DefaultConverterTypeName))
        {
            AppendStrictConversion(builder, property, GetSingleSpanExpression(method.SourceValueKind, valueName), "target." + property.Name, valueName + "c");
            return;
        }

        builder
            .Indent()
            .Append("target.")
            .Append(property.Name)
            .Append(" = ");
        AppendConvertCall(builder, property, GetSingleSpanExpression(method.SourceValueKind, valueName));
        builder.Append(";").NewLine();
    }

    private static void AppendConvertCall(SourceBuilder builder, PropertyModel property, string valueExpression)
    {
        builder
            .Append(property.ConverterMethodTypeName)
            .Append(".")
            .Append(property.ConverterMethodName!);

        // AssignmentTypeName is the element type for arrays, so the type argument is required for both scalars and arrays.
        if (property.IsEnum && (property.ConverterMethodTypeName == BindMethodModelBuilder.DefaultConverterTypeName))
        {
            builder
                .Append("<")
                .Append(property.AssignmentTypeName)
                .Append(">");
        }

        builder
            .Append("(")
            .Append(valueExpression)
            .Append(")");
    }

    private static void AppendStrictConversion(SourceBuilder builder, PropertyModel property, string valueExpression, string assignTarget, string tempName)
    {
        builder
            .Indent()
            .Append("if (!")
            .Append(property.ConverterMethodTypeName)
            .Append(".Try")
            .Append(property.ConverterMethodName!);

        if (property.IsEnum && (property.ConverterMethodTypeName == BindMethodModelBuilder.DefaultConverterTypeName))
        {
            builder
                .Append("<")
                .Append(property.AssignmentTypeName)
                .Append(">");
        }

        builder
            .Append("(")
            .Append(valueExpression)
            .Append(", out var ")
            .Append(tempName)
            .Append("))")
            .NewLine();
        builder.BeginScope();
        builder
            .Indent()
            .Append("throw new global::System.FormatException(\"Failed to convert property '")
            .Append(property.Name)
            .Append("'.\");")
            .NewLine();
        builder.EndScope();
        builder
            .Indent()
            .Append(assignTarget)
            .Append(" = ")
            .Append(tempName)
            .Append(";")
            .NewLine();
    }

    private static string GetArrayElementCreationType(string propertyTypeName, string assignmentTypeName)
    {
        var suffix = "[]";
        return propertyTypeName.EndsWith(suffix, StringComparison.Ordinal)
            ? propertyTypeName.Substring(0, propertyTypeName.Length - suffix.Length)
            : assignmentTypeName;
    }

    private static string GetHasValueExpression(string sourceValueKind, string valueName) => sourceValueKind switch
    {
        "StringValues" => $"({valueName}.Count > 0)",
        _ => $"({valueName} is not null)"
    };

    private static string GetSingleValueExpression(string sourceValueKind, string valueName) => sourceValueKind switch
    {
        "StringValues" => $"{valueName}[0]",
        _ => valueName
    };

    private static string GetSingleSpanExpression(string sourceValueKind, string valueName) => sourceValueKind switch
    {
        "StringValues" => $"{valueName}[0].AsSpan()",
        _ => $"{valueName}.AsSpan()"
    };

    private static string GetArrayValueExpression(string sourceValueKind, string valueName) => sourceValueKind switch
    {
        "StringValues" => $"{valueName}.ToArray()",
        _ => $"new[] {{ {valueName} }}"
    };

    private static string GetCountExpression(string sourceValueKind, string valueName) => sourceValueKind switch
    {
        "StringValues" => $"{valueName}.Count",
        _ => "1"
    };

    private static string GetIndexedSpanExpression(string sourceValueKind, string valueName, string indexName) => sourceValueKind switch
    {
        "StringValues" => $"{valueName}[{indexName}].AsSpan()",
        _ => $"{valueName}.AsSpan()"
    };

    // ------------------------------------------------------------
    // Helper
    // ------------------------------------------------------------

    public static string MakeFilename(string ns, string className)
    {
        var buffer = new StringBuilder();
        if (!String.IsNullOrEmpty(ns))
        {
            buffer.Append(ns.Replace('.', '_'));
            buffer.Append('_');
        }

        buffer.Append(className.Replace('<', '[').Replace('>', ']'));
        buffer.Append(".g.cs");
        return buffer.ToString();
    }
}
